# -*- coding: utf-8 -*-
"""效果命令类型全表（由 make_cmd_table.py 从 AGE3 源码 Lists.cpp 生成）。"""

CMD_TYPES = {
    0: {"en": 'Attribute Modifier (Set)', "zh": '0 - 属性修正（设置）'},
    1: {"en": 'Resource Modifier (Set/+/-)', "zh": '1 - 资源修正（设置/+/-）'},
    2: {"en": 'Enable/Disable Unit', "zh": '2 - 启用/禁用单位'},
    3: {"en": 'Upgrade Unit', "zh": '3 - 升级单位'},
    4: {"en": 'Attribute Modifier (+/-)', "zh": '4 - 属性修正（+/-）'},
    5: {"en": 'Attribute Modifier (Multiply)', "zh": '5 - 属性修正（乘法）'},
    6: {"en": 'Resource Modifier (Multiply)', "zh": '6 - 资源修正（乘法）'},
    7: {"en": 'Spawn Unit', "zh": '7 - 生成单位'},
    8: {"en": 'Modify Tech', "zh": '8 - 修改科技'},
    9: {"en": 'Set Player Civ Name', "zh": '9 - 设置玩家文明'},
    10: {"en": 'Team Attribute Modifier (Set)', "zh": '10 - 我方属性修正（设置）'},
    11: {"en": 'Team Resource Modifier (Set/+/-)', "zh": '11 - 我方资源修正（设置/+/-）'},
    12: {"en": 'Team Enable/Disable Unit', "zh": '12 - 队伍启用/禁用单位'},
    13: {"en": 'Team Upgrade Unit', "zh": '13 - 盟友升级单位'},
    14: {"en": 'Team Attribute Modifier (+/-)', "zh": '14 - 我方属性修正（+/-）'},
    15: {"en": 'Team Attribute Modifier (Multiply)', "zh": '15 - 我方属性修正（乘法）'},
    16: {"en": 'Team Resource Modifier (Multiply)', "zh": '16 - 我方资源修正（乘法）'},
    17: {"en": 'Team Spawn Unit', "zh": '17 - 队伍生成单位'},
    18: {"en": 'Team Modify Tech', "zh": '18 - 盟友修改科技'},
    19: {"en": 'Team Set Player Civ Name', "zh": '19 - 队伍设置玩家文明名'},
    20: {"en": 'Enemy Attribute Modifier (Set)', "zh": '20 - 敌方属性修正（设置）'},
    21: {"en": 'Enemy Resource Modifier (Set/+/-)', "zh": '21 - 敌方资源修正（设置/+/-）'},
    22: {"en": 'Enemy Enable/Disable Unit', "zh": '22 - 敌方启用/禁用单位'},
    23: {"en": 'Enemy Upgrade Unit', "zh": '23 - 敌方升级单位'},
    24: {"en": 'Enemy Attribute Modifier (+/-)', "zh": '24 - 敌方属性修正（+/-）'},
    25: {"en": 'Enemy Attribute Modifier (Multiply)', "zh": '25 - 敌方属性修正（乘法）'},
    26: {"en": 'Enemy Resource Modifier (Multiply)', "zh": '26 - 敌方资源修正（乘法）'},
    27: {"en": 'Enemy Spawn Unit', "zh": '27 - 敌方生产单位'},
    28: {"en": 'Enemy Modify Tech', "zh": '28 - 敌方修改科技'},
    29: {"en": 'Enemy Set Player Civ Name', "zh": '29 - 敌方设置玩家文明名'},
    30: {"en": 'Neutral Attribute Modifier (Set)', "zh": '30 - 中立属性修正（设置）'},
    31: {"en": 'Neutral Resource Modifier (Set/+/-)', "zh": '31 - 中立资源修正（设置/+/-）'},
    32: {"en": 'Neutral Enable/Disable Unit', "zh": '32 - 中立启用/禁用单位'},
    33: {"en": 'Neutral Upgrade Unit', "zh": '33 - 中立升级单位'},
    34: {"en": 'Neutral Attribute Modifier (+/-)', "zh": '34 - 中立属性修正（+/-）'},
    35: {"en": 'Neutral Attribute Modifier (Multiply)', "zh": '35 - 中立属性修正（乘法）'},
    36: {"en": 'Neutral Resource Modifier (Multiply)', "zh": '36 - 中立资源修正（乘法）'},
    37: {"en": 'Neutral Spawn Unit', "zh": '37 - 中立生产单位'},
    38: {"en": 'Neutral Modify Tech', "zh": '38 - 中立修改科技'},
    39: {"en": 'Neutral Set Player Civ Name', "zh": '39 - 中立设置文明'},
    40: {"en": 'Gaia Attribute Modifier (Set)', "zh": '40 - 盖亚属性修正（设置）'},
    41: {"en": 'Gaia Resource Modifier (Set/+/-)', "zh": '41 - 盖亚资源修正（设置/+/-）'},
    42: {"en": 'Gaia Enable/Disable Unit', "zh": '42 - 盖亚启用/禁用单位'},
    43: {"en": 'Gaia Upgrade Unit', "zh": '43 - 盖亚升级单位'},
    44: {"en": 'Gaia Attribute Modifier (+/-)', "zh": '44 - 盖亚属性修正（+/-）'},
    45: {"en": 'Gaia Attribute Modifier (Multiply)', "zh": '45 - 盖亚属性倍率'},
    46: {"en": 'Gaia Resource Modifier (Multiply)', "zh": '46 - 盖亚资源倍率'},
    47: {"en": 'Gaia Spawn Unit', "zh": '47 - 盖亚生成单位'},
    48: {"en": 'Gaia Modify Tech', "zh": '48 - 盖亚修改科技'},
    101: {"en": 'Tech Cost Modifier (Set/+/-)', "zh": '101 - 科技价格修改(设定/+/-)'},
    102: {"en": 'Disable Tech', "zh": '102 - 禁用科技'},
    103: {"en": 'Tech Time Modifier (Set/+/-)', "zh": '103 - 科技时间修改(设定/+/-)'},
    200: {"en": 'Own Master Objects Attribute Modifier (Set)', "zh": '200 - 自身主单位属性修改(设定)'},
    201: {"en": 'Own Master Objects Attribute Modifier (+/-)', "zh": '201 - 自身主单位属性修改(+/-)'},
    202: {"en": 'Own Master Objects Attribute Modifier (Multiply)', "zh": '202 - 自身主单位属性修改(乘)'},
    203: {"en": 'Selected Unit Attribute Modifier (Set)', "zh": '203 - 所选单位属性修改(设定)'},
    204: {"en": 'Selected Unit Attribute Modifier (+/-)', "zh": '204 - 所选单位属性修改(+/-)'},
    205: {"en": 'Selected Unit Attribute Modifier (Multiply)', "zh": '205 - 所选单位属性修改(乘)'},
    206: {"en": 'Transform Selected Unit', "zh": '206 - 变身所选单位'},
}

CMD_ZH = {n: (v["zh"] or v["en"]) for n, v in CMD_TYPES.items()}
CMD_EN = {n: v["en"] for n, v in CMD_TYPES.items()}

if __name__ == "__main__":
    for n in sorted(CMD_TYPES):
        print("%4d  %-48s %s" % (n, CMD_TYPES[n]["en"], CMD_TYPES[n]["zh"]))
